### ISSUE TITLE
should lock elm to 0.19.0

### ISSUE THREAD

**Issue by bencao** [cedricss/elm-batteries#3]
Currently in package.json

```
"elm": "^0.19.0-no-deps",
```

which resulted my local installation to resolve it as 0.19.1, and got the following error

```
-- ELM VERSION MISMATCH ----------------------------------------------- elm.json

Your elm.json says this application needs a different version of Elm.

It requires 0.19.0, but you are using 0.19.1 right now.

Dependencies ready!
```

we should lock the version instead

```
"elm": "0.19.0-no-deps",
```

**Comment by cedricss** [comment]
Thanks for the report!  

Instead of locking elm to 0.19.0, I just upgraded elm-batteries and the cli to elm 0.19.1:

https://github.com/cedricss/elm-batteries/releases/tag/1.1.1
https://www.npmjs.com/package/create-elm-batteries

To upgrade an existing project:

- Run `npm install elm@latest-0.19.1 --save-dev` 
- Add the latest `elm-test` locally with `npm install elm-test --save-dev` (it can only be used with elm `0.19.1`)
- Change to `"elm-version": "0.19.1"` in your `elm.json`
